[options]
name = "10.0eV_45deg_N2_Ti_"
track_trajectories = true
track_recoils = true
track_recoil_trajectories = true
write_buffer_size = 8000
weak_collision_order = 3
suppress_deep_recoils = false
high_energy_free_flight_paths = false
electronic_stopping_mode = "LOW_ENERGY_NONLOCAL"
mean_free_path_model = "LIQUID"
interaction_potential = [["KR_C"]]
scattering_integral = [["MENDENHALL_WELLER"]]
use_hdf5 = false
root_finder = [[{"NEWTON"={max_iterations=100, tolerance=1E-6}}]]
num_threads = 4
num_chunks = 1
track_displacements = false
track_energy_losses = true
energy_min = 0.0
energy_max = 10.0
energy_num = 20
angle_min = 45.0
angle_max = 45.0
angle_num = 1
x_min = -5.0
y_min = -0.1
z_min = -0.1
x_max = 1.0
y_max = 0.1
z_max = 0.1
x_num = 20
y_num = 20
z_num = 20

[particle_parameters]
length_unit = "1e-6"
energy_unit = "EV"
mass_unit = "AMU"
N = [ 100,]
m = [ 28.0134,]
Z = [ 7,]
E = [ 20.0,]
Ec = [ 1.0,]
Es = [ 0.0,]
interaction_index = [0]
pos = [ [ -1.7453292519934434e-8, 0.0, 0.0,],]
dir = [ [ 0.999, 0.001, 0.0,],]

[geometry_input]
length_unit = "MICRON"
triangles = [ [ 0.0, 0.01, 0.0, 0.5, 0.5, -0.5,],]
densities = [ [ 3.0e+10, 6.0e+10, 0.0, 0.0,],]
material_boundary_points = [ [ 0.0, 0.5,],]
simulation_boundary_points = [ [ 0.6, -0.6,],]
electronic_stopping_correction_factors = [1.0]
energy_barrier_thickness = 2.2E-4

[material_parameters]
energy_unit = "EV"
mass_unit = "AMU"
Eb = [ 3.0,]
Es = [ 4.84,]
Ec = [ 3.5,]
Z = [ 22,]
m = [ 47.867,]
interaction_index = [0,]
surface_binding_model = {"PLANAR"={calculation="TARGET"}}
bulk_binding_model = "AVERAGE"
